# IADSS Signal Tracker
# https://github.com/ballzac81/IADSS-Signal-Tracker

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: IADSS_freqtrade
    restart: unless-stopped
    ports:
      - "8067:8080"
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy WebhookStrategy

  signal-tracker:
    image: burgess22/signal-tracker
    container_name: IADSS_signal_tracker
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - SECRET_TOKEN=CHANGE_THIS_TO_RANDOM_STRING
      - TELEGRAM_TOKEN=CHANGE_THIS_TO_YOUR_TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID=CHANGE_THIS_TO_YOUR_TELEGRAM_CHAT_ID
      - FREQTRADE_API=http://freqtrade:8080/api/v1
      - FREQTRADE_USER=admin
      - FREQTRADE_PASS=CHANGE_THIS_TO_YOUR_FREQTRADE_PASSWORD
      - STAKE_RATIO=0.5
      - SELL_RATIO=0.5
      - MIN_STAKE=10
