#!/usr/bin/env bash
# IADSS setup script — generates secrets, collects config, writes .env and user_data
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✔${NC}  $*"; }
warn() { echo -e "${YELLOW}⚠${NC}  $*"; }
err()  { echo -e "${RED}✖${NC}  $*" >&2; exit 1; }
info() { echo -e "${CYAN}ℹ${NC}  $*"; }

echo ""
echo "═══════════════════════════════════════════"
echo "   IADSS Signal Tracker — Setup"
echo "═══════════════════════════════════════════"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v docker  >/dev/null 2>&1 || err "Docker not found. See README Part 1 for install instructions."
command -v openssl >/dev/null 2>&1 || err "openssl not found (needed to generate secrets)"
ok "Docker found: $(docker --version | head -1)"

# ── Guard against overwriting ─────────────────────────────────────────────────
if [ -f .env ]; then
    warn ".env already exists."
    read -rp "   Overwrite? [y/N] " REPLY
    [[ ! $REPLY =~ ^[Yy]$ ]] && { echo "Aborted."; exit 0; }
    echo ""
fi

# ── Generate secrets ──────────────────────────────────────────────────────────
SECRET_TOKEN=$(openssl rand -hex 24)
FREQTRADE_PASS=$(openssl rand -hex 16)
FREQTRADE_JWT=$(openssl rand -hex 32)
ok "Secrets generated"

# ── Setup path ────────────────────────────────────────────────────────────────
echo ""
echo "Setup path"
echo "──────────"
echo "  1) VPS (Cloud server with Caddy — auto HTTPS)"
echo "  2) Self-hosted (Unraid / NAS / home server / Pi — Cloudflare Tunnel)"
echo ""
read -rp "  Choose [1/2]: " PATH_CHOICE
case "$PATH_CHOICE" in
    2) SETUP_PATH="selfhosted" ;;
    *) SETUP_PATH="vps" ;;
esac
ok "Path: $SETUP_PATH"

# ── Domains ───────────────────────────────────────────────────────────────────
echo ""
echo "Domains"
echo "───────"
if [ "$SETUP_PATH" = "selfhosted" ]; then
    info "Cloudflare Tunnel creates HTTPS automatically."
    info "Configure two Public Hostnames in the Cloudflare tunnel dashboard:"
    info "  signals.yourdomain.com → http://signal-tracker:5000"
    info "  trade.yourdomain.com   → http://freqtrade:8080"
    echo ""
else
    info "Both domains need DNS A records pointing at your VPS IP."
    info "Ports 80 and 443 must be open in your firewall."
    echo ""
fi

read -rp "  Signal tracker domain (e.g. signals.yourdomain.com): " SIGNAL_DOMAIN
[ -z "$SIGNAL_DOMAIN" ] && err "Signal domain cannot be blank"

read -rp "  Freqtrade UI domain   (e.g. trade.yourdomain.com):   " FREQTRADE_DOMAIN
[ -z "$FREQTRADE_DOMAIN" ] && err "Freqtrade domain cannot be blank"

# ── Cloudflare tunnel token + Docker network (self-hosted only) ───────────────
CF_TOKEN=""
DOCKER_NETWORK=""
if [ "$SETUP_PATH" = "selfhosted" ]; then
    echo ""
    echo "Cloudflare Tunnel"
    echo "─────────────────"
    info "If you have an existing Cloudflare Tunnel container running, leave token blank."
    info "Otherwise go to Cloudflare Zero Trust → Networks → Tunnels → Create tunnel."
    echo ""
    read -rp "  Tunnel token (or press Enter to skip if already running): " CF_TOKEN

    echo ""
    echo "Docker network"
    echo "──────────────"
    info "The Docker network your Cloudflare Tunnel container runs on."
    info "On Unraid: Settings → Docker → your custom network name"
    echo ""
    read -rp "  Docker network name (or press Enter to skip if using bundled cloudflared): " DOCKER_NETWORK
    [ -z "$DOCKER_NETWORK" ] && warn "No network set — make sure to uncomment the cloudflared service in docker-compose.selfhosted.yml"
fi

# ── Exchange ──────────────────────────────────────────────────────────────────
echo ""
echo "Exchange"
echo "────────"
read -rp "  Exchange name (kraken / binance / coinbase) [kraken]: " EXCHANGE
EXCHANGE="${EXCHANGE:-kraken}"

read -rp "  API Key: " API_KEY
[ -z "$API_KEY" ] && err "API key cannot be blank"

read -rsp "  API Secret: " API_SECRET
echo ""
[ -z "$API_SECRET" ] && err "API secret cannot be blank"

# ── Trading pair ──────────────────────────────────────────────────────────────
echo ""
echo "Trading pair"
echo "────────────"
read -rp "  Primary pair [SOL/USD]: " PAIR
PAIR="${PAIR:-SOL/USD}"

# ── Signal window ─────────────────────────────────────────────────────────────
echo ""
echo "Signal window"
echo "─────────────"
echo "  4h x 10 candles = 144000 s | 1h x 10 candles = 36000 s"
read -rp "  WINDOW_SECONDS [144000]: " WINDOW
WINDOW="${WINDOW:-144000}"

# ── Telegram ──────────────────────────────────────────────────────────────────
echo ""
echo "Telegram (optional — press Enter to skip)"
echo "─────────────────────────────────────────"
read -rp "  Bot token: " TG_TOKEN
TG_CHAT=""
if [ -n "$TG_TOKEN" ]; then
    read -rp "  Chat ID: " TG_CHAT
    [ -z "$TG_CHAT" ] && warn "No chat ID — Telegram disabled"
fi

# ── Write .env ────────────────────────────────────────────────────────────────
cat > .env << EOF
# Generated by setup.sh — $(date)
# DO NOT commit this file.

SETUP_PATH=$SETUP_PATH
SIGNAL_DOMAIN=$SIGNAL_DOMAIN
FREQTRADE_DOMAIN=$FREQTRADE_DOMAIN
CLOUDFLARE_TUNNEL_TOKEN=$CF_TOKEN
DOCKER_NETWORK=$DOCKER_NETWORK

SECRET_TOKEN=$SECRET_TOKEN
FREQTRADE_PASS=$FREQTRADE_PASS
FREQTRADE_JWT_SECRET=$FREQTRADE_JWT

EXCHANGE_NAME=$EXCHANGE
EXCHANGE_API_KEY=$API_KEY
EXCHANGE_API_SECRET=$API_SECRET

TELEGRAM_TOKEN=$TG_TOKEN
TELEGRAM_CHAT_ID=$TG_CHAT

TRADING_PAIR=$PAIR
WINDOW_SECONDS=$WINDOW
DRY_RUN=true
EOF
ok ".env written"

# ── user_data directories ─────────────────────────────────────────────────────
mkdir -p user_data/strategies user_data/logs user_data/data
ok "user_data/ directories created"

# ── Generate user_data/config.json ───────────────────────────────────────────
# Uses sed so python3 is not required (works on Unraid and minimal systems)
if [ -f config.json ]; then
    _escape() { printf '%s' "$1" | sed 's/[\/&]/\\&/g'; }
    EXCHANGE_ESC=$(_escape "$EXCHANGE")
    API_KEY_ESC=$(_escape "$API_KEY")
    API_SECRET_ESC=$(_escape "$API_SECRET")
    PAIR_ESC=$(_escape "$PAIR")
    TG_TOKEN_ESC=$(_escape "$TG_TOKEN")
    TG_CHAT_ESC=$(_escape "$TG_CHAT")
    FREQTRADE_PASS_ESC=$(_escape "$FREQTRADE_PASS")
    FREQTRADE_JWT_ESC=$(_escape "$FREQTRADE_JWT")

    if [ -n "$TG_TOKEN" ] && [ -n "$TG_CHAT" ]; then
        TG_ENABLED="true"
    else
        TG_ENABLED="false"
    fi

    sed \
        -e "s/YOUR_EXCHANGE_API_KEY/$API_KEY_ESC/" \
        -e "s/YOUR_EXCHANGE_API_SECRET/$API_SECRET_ESC/" \
        -e "s/\"name\": \"kraken\"/\"name\": \"$EXCHANGE_ESC\"/" \
        -e "s/\"SOL\/USD\"/\"$PAIR_ESC\"/g" \
        -e "s/YOUR_TELEGRAM_BOT_TOKEN/$TG_TOKEN_ESC/" \
        -e "s/YOUR_TELEGRAM_CHAT_ID/$TG_CHAT_ESC/" \
        -e "s/\"enabled\": true/\"enabled\": $TG_ENABLED/" \
        -e "s/CHANGE_THIS_TO_YOUR_PASSWORD/$FREQTRADE_PASS_ESC/" \
        -e "s/CHANGE_THIS_TO_RANDOM_32_CHAR_STRING/$FREQTRADE_JWT_ESC/" \
        config.json > user_data/config.json
    ok "user_data/config.json generated"
else
    warn "config.json not found — skipping user_data/config.json generation"
fi

# ── Copy strategy ─────────────────────────────────────────────────────────────
if [ -f strategies/WebhookStrategy.py ]; then
    cp strategies/WebhookStrategy.py user_data/strategies/
    ok "WebhookStrategy.py copied"
fi

# ── Gitignore .env ────────────────────────────────────────────────────────────
if [ -f .gitignore ]; then
    grep -q '^\.env$' .gitignore || echo '.env' >> .gitignore
else
    echo '.env' > .gitignore
fi
ok ".env added to .gitignore"

# ── Determine compose file ────────────────────────────────────────────────────
if [ "$SETUP_PATH" = "selfhosted" ]; then
    COMPOSE_CMD="docker compose -f docker-compose.selfhosted.yml"
else
    COMPOSE_CMD="docker compose"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════"
echo -e "   ${GREEN}Setup complete!${NC}"
echo "═══════════════════════════════════════════"
echo ""

if [ "$SETUP_PATH" = "vps" ]; then
    echo "  Before starting, make sure:"
    echo "  • $SIGNAL_DOMAIN → this server's public IP (DNS A record)"
    echo "  • $FREQTRADE_DOMAIN → this server's public IP (DNS A record)"
    echo "  • Ports 80 and 443 are open in your firewall"
    echo ""
else
    echo "  Before starting, make sure:"
    echo "  • Cloudflare tunnel is Active in your Zero Trust dashboard"
    echo "  • Public Hostnames are configured in the tunnel:"
    echo "    $SIGNAL_DOMAIN  → http://signal-tracker:5000"
    echo "    $FREQTRADE_DOMAIN → http://freqtrade:8080"
    echo ""
fi

echo "  Freqtrade UI:  https://$FREQTRADE_DOMAIN"
echo "  Username:      admin"
echo "  Password:      $FREQTRADE_PASS"
echo ""
echo "  Signal status: https://$SIGNAL_DOMAIN/status?token=$SECRET_TOKEN"
echo ""
echo "  TradingView webhook example:"
echo "  https://$SIGNAL_DOMAIN/mr-buy"
echo ""
echo "  Running in DRY RUN mode."
echo "  To go live: edit user_data/config.json → set dry_run: false → restart"
echo ""
echo "  Start:  $COMPOSE_CMD up -d"
echo "  Logs:   $COMPOSE_CMD logs -f"
echo ""
